### ISSUE TITLE
Team images hover effect

### ISSUE THREAD

**Issue by evelynhathaway** [sensolcrosswalks/sensolcrosswalks.github.io#1]
Just to document a future enhancement we discussed.

```css
.team-img {
	// Transition the filter property
	transition: filter .3s ease-in;
}
.team-img:hover {
	// Make the image black and white on hover
	filter: saturate(0);
}
```
